server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  mvc:
    log-request-details: false
  application:
    name: dynamic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      first:
        url: jdbc:mysql://localhost:3306/jssh?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456,
      second:
        url: jdbc:mysql://localhost:3306/jsshtest?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456,

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml