CREATE TABLE `user` (
                      `id` bigint(11) NOT NULL AUTO_INCREMENT,
                      `username` varchar(20) DEFAULT NULL COMMENT '用户名',
                      `password` varchar(20) DEFAULT NULL COMMENT '密码',
                      `name` varchar(16) DEFAULT NULL COMMENT '真实姓名',
                      `post` varchar(20) DEFAULT NULL COMMENT '岗位',
                      `role_id` bigint(11) DEFAULT NULL COMMENT '角色id',
                      `role_name` varchar(20) DEFAULT NULL COMMENT '角色名称',
                      `mail` varchar(50) DEFAULT NULL COMMENT '邮箱',
                      `mobile` varchar(20) DEFAULT NULL COMMENT '手机号码',
                      `department_mobile` varchar(20) DEFAULT NULL COMMENT '部门电话',
                      `group_name` varchar(50) DEFAULT NULL COMMENT '所属集团',
                      `company_name` varchar(50) DEFAULT NULL COMMENT '所属公司',
                      `project_department_name` varchar(50) DEFAULT NULL COMMENT '所属项目部',
                      `maintain_department_name` varchar(50) DEFAULT NULL COMMENT '所属维修部',
                      `sn_code` varchar(50) DEFAULT NULL COMMENT 's/n码',
                      `is_online` int(1) DEFAULT NULL COMMENT '是否在线  0、离线 1、在线',
                      `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
                      `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
                      `station_name` varchar(30) DEFAULT NULL COMMENT '站点',
                      `line_name` varchar(30) DEFAULT NULL COMMENT '线路',
                      `type` int(1) DEFAULT NULL COMMENT '修改类型1、消息2、震动',
                      `flag` int(1) DEFAULT NULL COMMENT '标记类型0、关1、开',
                      `message_flag` int(1) DEFAULT NULL COMMENT '消息接收状态0、不接收1、接收',
                      `shake_flag` int(1) DEFAULT NULL COMMENT '震动提示状态0、不接收1、接收',
                      `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                      `station_id` varchar(10) DEFAULT NULL COMMENT '站点id',
                      `line_id` varchar(10) DEFAULT NULL COMMENT '线路id',
                      `pic` varchar(200) DEFAULT NULL,
                      `uid` varchar(255) DEFAULT 'NULL' COMMENT '账号ID',
                      `pswd` varchar(255) DEFAULT 'NULL' COMMENT '明文密码',
                      `cn` varchar(255) DEFAULT 'NULL' COMMENT '中文姓名',
                      `sn` varchar(255) DEFAULT 'NULL' COMMENT '姓名拼音',
                      `deptno` varchar(255) DEFAULT 'NULL' COMMENT '所属部门编码',
                      `sortorder` varchar(255) DEFAULT 'NULL' COMMENT '人员排序号',
                      `securitylevel` varchar(255) DEFAULT 'NULL' COMMENT '人员密级',
                      `securitytype` varchar(255) DEFAULT 'NULL' COMMENT '涉密类型',
                      `position` varchar(255) DEFAULT 'NULL' COMMENT '岗位',
                      `status` varchar(255) DEFAULT 'NULL' COMMENT '用户状态1:启用  0锁定',
                      `accstatus` varchar(255) DEFAULT 'NULL' COMMENT '数据状态1：启用  0：删除、锁定。Status和accStatus同时为1，则该账号可用。任意一个为0，则账号不可用。',
                      PRIMARY KEY (`id`),
                      KEY `role_id_index` (`role_id`) USING BTREE,
                      KEY `idx_mobile` (`mobile`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=618 DEFAULT CHARSET=utf8;

